### ISSUE TITLE
Please remove my textures from the mod.

### ISSUE THREAD

**Issue by KrimsonKolbolt** [thatoneaiguy/rosel#3]
This is one last warning for you to stop using my textures. Thank you.

**Comment by eeverestt** [comment]
When you asked me, i have told you, i am getting new textures for rosel ( See figure one )

![figure two](https://github.com/user-attachments/assets/632d33e8-dcb7-445a-8192-8ad5ecde4a5b)

and also, in this message, you told me, and I quote, " [...] , you don't have to if you don't want to ". I've asked you to stop, please, i have offered you to sort things out in a controlled environment ( See figure two )

![figure two](https://github.com/user-attachments/assets/79745b7f-809e-4ef6-897f-982fed1a9229)

, and you haven't replied anything about it since. Please, I don't want to have to argue, but i have had to make preperations since I know you have used my code unconsentually in the past. In addition, we have never been the person or group to start contact, and have taken time out of our day to reply to you, please, check the carved releases group and reply to me, maybe we can talk.
